replicaCount: 1

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-public
    cert-manager.io/cluster-issuer: letsencrypt-dns
  path: /
  host: stylebook-prod.appfollow.io
  tls:
    - hosts:
        - stylebook-prod.appfollow.io
      secretName: appfollow-wildcard

environment: {}

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
