replicaCount: 1

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-public
    cert-manager.io/cluster-issuer: letsencrypt-dns
  path: /
  host: ui-kit.rancher-prod-public.appfollow.io
  tls:
    - hosts:
        - ui-kit.rancher-prod-public.appfollow.io
      secretName: ui-kit-tls

environment: {}

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
