replicaCount: 1

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx-public
    ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  path: /
  host: ui-kit.rancher-dev-public.appfollow.io
  tls:
    - hosts:
        - ui-kit.rancher-dev-public.appfollow.io
      secretName: ui-kit-tls

environment: {}

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 128Mi

autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}
